Tela de gerencimaneto de professores  - (CRUD)
mdsreq-fga-unb/2024.1-ObjeX pull request #58
Opened 2024-08-30 14:40 UTC by Nicollaxs

# Pull Request

## 📖 Descrição

### 🎫 Issues

## 👩‍💻 Review

2024-08-30 19:48 UTC, FabricioDeQueiroz requested changes
Aguardemos resolver a questão da Turma...

2024-08-30 19:48 UTC, FabricioDeQueiroz commented on src/pages/lista-professores/ListaDeProfessores.jsx
> +        await axios.put(`${API_BASE_URL}/professor/update`,
Meu bom, acho que os dados a serem atualizados são o Nome, Turma e o Cargo... O email a API ignora, mas no modal tem que ter como mudar o Cargo e a Turma. Mas claro, acho que nem compensa preocupar com isso ainda, a gente tem que ver o que vai fazer com a questão da Turma.

2024-09-03 16:45 UTC, cwtshh commented
Acho que já da pra aprovar, não?

2024-09-04 12:17 UTC, FabricioDeQueiroz commented
> Acho que já da pra aprovar, não?

Acho que o Nicollas ainda vai corrigir a parada da Turma do  Professor.

2024-09-06 17:35 UTC, FabricioDeQueiroz approved these changes

2024-09-06 17:35 UTC, merged